server:
  port: 8585

spring:
#  liquibase:
#    change-log: liquibase/changelog-master.yml
#    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/uniTech
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jakarta:
          persistence:
            sharedCache:
              mode: ENABLE_SELECTIVE