server:
  port: 8585
  servlet:
    context-path: /security

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uniTech
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jakarta:
          persistence:
            sharedCache:
              mode: ENABLE_SELECTIVE

currency:
  api:
    key: 6cf4a0dbeddf7c5903e365f1
    url: https://open.er-api.com/v6/latest


  #  liquibase:
  #    change-log: liquibase/changelog-master.yml
  #    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ilqardrob@gmail.com
    password: "Ilqar0515001740"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true



